/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace FrameworkRegistry {
  export type FrameworkEntryStruct = {
    name: string;
    version: string;
    repoUrl: string;
    registrant: AddressLike;
    registeredAt: BigNumberish;
  };

  export type FrameworkEntryStructOutput = [
    name: string,
    version: string,
    repoUrl: string,
    registrant: string,
    registeredAt: bigint
  ] & {
    name: string;
    version: string;
    repoUrl: string;
    registrant: string;
    registeredAt: bigint;
  };
}

export interface FrameworkRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getFramework"
      | "getRegistrantAt"
      | "getRegistrantCount"
      | "getSyncHash"
      | "registerFramework"
      | "setSyncHash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FrameworkRegistered" | "SyncHashUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getFramework",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistrantAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistrantCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getSyncHash", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerFramework",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setSyncHash",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getFramework",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegistrantAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegistrantCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSyncHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerFramework",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSyncHash",
    data: BytesLike
  ): Result;
}

export namespace FrameworkRegisteredEvent {
  export type InputTuple = [
    registrant: AddressLike,
    name: string,
    version: string,
    repoUrl: string
  ];
  export type OutputTuple = [
    registrant: string,
    name: string,
    version: string,
    repoUrl: string
  ];
  export interface OutputObject {
    registrant: string;
    name: string;
    version: string;
    repoUrl: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SyncHashUpdatedEvent {
  export type InputTuple = [
    projectKey: string,
    fileHash: string,
    updater: AddressLike
  ];
  export type OutputTuple = [
    projectKey: string,
    fileHash: string,
    updater: string
  ];
  export interface OutputObject {
    projectKey: string;
    fileHash: string;
    updater: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FrameworkRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): FrameworkRegistry;
  waitForDeployment(): Promise<this>;

  interface: FrameworkRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFramework: TypedContractMethod<
    [registrant: AddressLike],
    [FrameworkRegistry.FrameworkEntryStructOutput],
    "view"
  >;

  getRegistrantAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getRegistrantCount: TypedContractMethod<[], [bigint], "view">;

  getSyncHash: TypedContractMethod<[projectKey: string], [string], "view">;

  registerFramework: TypedContractMethod<
    [name: string, version: string, repoUrl: string],
    [void],
    "nonpayable"
  >;

  setSyncHash: TypedContractMethod<
    [projectKey: string, fileHash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getFramework"
  ): TypedContractMethod<
    [registrant: AddressLike],
    [FrameworkRegistry.FrameworkEntryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRegistrantAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getRegistrantCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSyncHash"
  ): TypedContractMethod<[projectKey: string], [string], "view">;
  getFunction(
    nameOrSignature: "registerFramework"
  ): TypedContractMethod<
    [name: string, version: string, repoUrl: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSyncHash"
  ): TypedContractMethod<
    [projectKey: string, fileHash: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FrameworkRegistered"
  ): TypedContractEvent<
    FrameworkRegisteredEvent.InputTuple,
    FrameworkRegisteredEvent.OutputTuple,
    FrameworkRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "SyncHashUpdated"
  ): TypedContractEvent<
    SyncHashUpdatedEvent.InputTuple,
    SyncHashUpdatedEvent.OutputTuple,
    SyncHashUpdatedEvent.OutputObject
  >;

  filters: {
    "FrameworkRegistered(address,string,string,string)": TypedContractEvent<
      FrameworkRegisteredEvent.InputTuple,
      FrameworkRegisteredEvent.OutputTuple,
      FrameworkRegisteredEvent.OutputObject
    >;
    FrameworkRegistered: TypedContractEvent<
      FrameworkRegisteredEvent.InputTuple,
      FrameworkRegisteredEvent.OutputTuple,
      FrameworkRegisteredEvent.OutputObject
    >;

    "SyncHashUpdated(string,string,address)": TypedContractEvent<
      SyncHashUpdatedEvent.InputTuple,
      SyncHashUpdatedEvent.OutputTuple,
      SyncHashUpdatedEvent.OutputObject
    >;
    SyncHashUpdated: TypedContractEvent<
      SyncHashUpdatedEvent.InputTuple,
      SyncHashUpdatedEvent.OutputTuple,
      SyncHashUpdatedEvent.OutputObject
    >;
  };
}
