/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FrameworkRegistry } from "./FrameworkRegistry";
export * as factories from "./factories";
export { FrameworkRegistry__factory } from "./factories/FrameworkRegistry__factory";
